package pdf

import (
	"bytes"
	"fmt"

	"github.com/go-pdf/fpdf"
	"github.com/smetanamolokovich/veylo/internal/application/report"
)

type VehicleReportGenerator struct{}

func NewVehicleReportGenerator() *VehicleReportGenerator {
	return &VehicleReportGenerator{}
}

func (g *VehicleReportGenerator) Generate(data report.ReportData) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AddPage()

	pageW, _ := pdf.GetPageSize()
	contentW := pageW - 30

	// Header
	pdf.SetFont("Arial", "B", 20)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(contentW, 10, "Vehicle Inspection Report", "", 1, "C", false, 0, "")
	pdf.Ln(2)

	pdf.SetFont("Arial", "", 10)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(contentW, 6, data.OrgName, "", 1, "C", false, 0, "")
	pdf.CellFormat(contentW, 6, "Generated: "+data.GeneratedAt.Format("02 Jan 2006 15:04"), "", 1, "C", false, 0, "")
	pdf.Ln(4)

	// Divider
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(15, pdf.GetY(), pageW-15, pdf.GetY())
	pdf.Ln(5)

	// Inspection info section
	g.sectionHeader(pdf, "Inspection Details")
	g.row(pdf, contentW, "Inspection ID", data.InspectionID)
	g.row(pdf, contentW, "Contract Number", data.ContractNumber)
	g.row(pdf, contentW, "Status", data.Status)
	g.row(pdf, contentW, "Date", data.InspectionDate.Format("02 Jan 2006"))
	pdf.Ln(4)

	// Vehicle info section
	g.sectionHeader(pdf, "Vehicle Information")
	g.row(pdf, contentW, "VIN", data.VIN)
	g.row(pdf, contentW, "License Plate", data.LicensePlate)
	g.row(pdf, contentW, "Brand / Model", data.Brand+" "+data.Model)
	g.row(pdf, contentW, "Body Type", data.BodyType)
	g.row(pdf, contentW, "Fuel Type", data.FuelType)
	g.row(pdf, contentW, "Transmission", data.Transmission)
	g.row(pdf, contentW, "Color", data.Color)
	g.row(pdf, contentW, "Odometer", fmt.Sprintf("%d km", data.OdometerReading))
	g.row(pdf, contentW, "Engine Power", fmt.Sprintf("%d HP", data.EnginePower))
	pdf.Ln(4)

	// Findings section
	g.sectionHeader(pdf, fmt.Sprintf("Findings (%d)", len(data.Findings)))
	if len(data.Findings) == 0 {
		pdf.SetFont("Arial", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(contentW, 8, "No findings recorded.", "", 1, "L", false, 0, "")
	} else {
		g.findingsTable(pdf, contentW, data.Findings)
	}
	pdf.Ln(4)

	// Cost Summary
	g.sectionHeader(pdf, "Cost Summary")
	totalCents := 0
	for _, f := range data.Findings {
		totalCents += f.TotalCost
	}
	g.row(pdf, contentW, "Total Repair Cost", fmt.Sprintf("€ %.2f", float64(totalCents)/100))
	pdf.Ln(8)

	// Footer
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(150, 150, 150)
	pdf.CellFormat(contentW, 6, "Generated by Veylo — Universal Inspection Management Platform", "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("pdf.Generate: %w", err)
	}
	return buf.Bytes(), nil
}

func (g *VehicleReportGenerator) sectionHeader(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Arial", "B", 12)
	pdf.SetTextColor(50, 50, 50)
	pdf.SetFillColor(240, 240, 240)
	_, pageH := pdf.GetPageSize()
	if pdf.GetY() > pageH-40 {
		pdf.AddPage()
	}
	pdf.CellFormat(0, 8, "  "+title, "LB", 1, "L", true, 0, "")
	pdf.Ln(2)
}

func (g *VehicleReportGenerator) row(pdf *fpdf.Fpdf, width float64, label, value string) {
	col := width / 2
	pdf.SetFont("Arial", "B", 9)
	pdf.SetTextColor(80, 80, 80)
	pdf.CellFormat(col, 7, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(col, 7, value, "", 1, "L", false, 0, "")
}

func (g *VehicleReportGenerator) findingsTable(pdf *fpdf.Fpdf, width float64, findings []report.FindingData) {
	// Table header
	pdf.SetFont("Arial", "B", 8)
	pdf.SetFillColor(220, 220, 220)
	pdf.SetTextColor(30, 30, 30)

	cols := []float64{35, 30, 30, 35, 40}
	headers := []string{"Location", "Type", "Severity", "Repair", "Cost (€)"}
	for i, h := range headers {
		pdf.CellFormat(cols[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Arial", "", 8)
	pdf.SetFillColor(255, 255, 255)

	for idx, f := range findings {
		if pdf.GetY() > 260 {
			pdf.AddPage()
		}
		fill := idx%2 == 0
		if fill {
			pdf.SetFillColor(250, 250, 250)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		severity := "-"
		if f.Severity != "" {
			severity = f.Severity
		}
		repairMethod := "-"
		if f.RepairMethod != "" {
			repairMethod = f.RepairMethod
		}
		cost := fmt.Sprintf("%.2f", float64(f.TotalCost)/100)

		pdf.CellFormat(cols[0], 6, f.BodyArea, "1", 0, "L", fill, 0, "")
		pdf.CellFormat(cols[1], 6, f.FindingType, "1", 0, "L", fill, 0, "")
		pdf.CellFormat(cols[2], 6, severity, "1", 0, "C", fill, 0, "")
		pdf.CellFormat(cols[3], 6, repairMethod, "1", 0, "C", fill, 0, "")
		pdf.CellFormat(cols[4], 6, cost, "1", 0, "R", fill, 0, "")
		pdf.Ln(-1)
	}
}
