CREATE TABLE users (                                                                                                                                                                                                                                        
      id              VARCHAR(26) PRIMARY KEY,                                                                                                                                                                                                                
      organization_id VARCHAR(26) NOT NULL,                                                                                                                                                                                                                   
      email           VARCHAR(255) NOT NULL,                                                                                                                                                                                                                  
      password_hash   VARCHAR(255) NOT NULL,                                                                                                                                                                                                                  
      full_name       VARCHAR(255) NOT NULL,                                                                                                                                                                                                                  
      role            VARCHAR(50) NOT NULL,
      status          VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',                                                                                                                                                                                                  
      created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),                                                                                                                                                                                                     
      updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()                                                                                                                                                                                                      
  );                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                              
  CREATE UNIQUE INDEX idx_users_email_org ON users (email, organization_id);
  CREATE INDEX idx_users_organization_id ON users (organization_id);